
import "../style/globals.css";
import { Toaster } from "react-hot-toast";
import Provider from "../Provider";
import Header from "@/components/Header";
import AdminSidebar from "@/components/AdminSidbar";

export const metadata = {
  title: {
    template: '%s|نکست شاپ ',
    default: 'نکست شاپ'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body

      >

        <Provider>
          <div className="font-display">
            <Header />
          </div>
          <div className="font-display grid grid-cols-4 gap-4 min-h-screen">
            <Toaster />


            <div className="col-span-1  p-4">
              <AdminSidebar />
              </div>
              <div className="col-span-3 bg-white p-4">

                {children}
            </div>
   
          </div>
        </Provider>

      </body>
    </html >
  );
}
