
import "../../style/globals.css";
import { Toaster } from "react-hot-toast";
import Provider from "../../Provider";

export const metadata = {
  title: "پنل ادمین",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body
      >
        <div className="font-display">
          <Toaster />
          <Provider>
     
            {children}
            </Provider>
        </div>

      </body>
    </html>
  );
}
