import "../style/globals.css";
import { Toaster } from "react-hot-toast";
import Provider from "../Provider";
import Header from "@/components/Header";
import Footer from "@/components/ui/Footer";

export const metadata = {
  title: {
    template: '%s|نکست شاپ ',
    default: 'نکست شاپ'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">

      <body className="flex flex-col min-h-screen">
        <div className="font-display flex flex-col flex-1">
          <Toaster />
          <Provider>
            <Header />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </Provider>
        </div>
      </body>
    </html>
  );
}