
import "../style/globals.css";
import { Toaster } from "react-hot-toast";
import Provider from "../Provider";
import Header from "@/components/Header";
export const metadata = {
  title: {
    template: '%s|نکست شاپ ',
    default: 'نکست شاپ'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body

      >
        <div className="font-display">
          <Toaster />
          <Provider>
            <Header />
            {children}
            </Provider>
        </div>

      </body>
    </html>
  );
}
