import "../style/globals.css";
import { Toaster } from "react-hot-toast";

import SideBar from "@/components/SideBar";
import Provider from "app/Provider";
import Footer from "@/components/ui/Footer";
export const metadata = {
  title: {
    template: "%s|نکست شاپ ",
    default: "نکست شاپ",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <div className="font-display">
          <Toaster />
          <Provider>
            <div className="grid grid-cols-4 gap-4 min-h-screen">
              <div className="col-span-1 bg-gray-200 p-4">
                <SideBar />
              </div>

              <div className="col-span-3 bg-white p-4">
                {children}
              </div>
            </div>
                <Footer />
          </Provider>
        </div>
      </body>
    </html>
  );
}
