
import "../style/globals.css";
import { Toaster } from "react-hot-toast";
import Provider from "../Provider";
import SideBar from "@/components/SideBar";

export const metadata = {
  title: "پروفابل",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
      >
        <div className="font-display grid grid-cols-4 bg-white h-screen">
          <div className=" col-span-1 bg-gray-100 overflow-y-auto p-4">
            <Toaster />
            <SideBar/>
              </div>
            <Provider>
              <div className="col-span-3 overflow-y-auto p-4">
                {children}
              </div>
            </Provider>
          
        </div>
      </body>
    </html>
  );
}
