import "./style/globals.css";
import Header from "./components/Header";
import { Toaster } from "react-hot-toast";
import Provider from "./Provider";



export const metadata = {
  title: {
    template: '%s|نکست شاپ ',
    default: 'نکست شاپ'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body
      >
        <div className="font-display">
          <Toaster />

          <Header />
          <Provider>{children}</Provider>
        </div>

      </body>
    </html>
  );
}
