import "./style/globals.css";
import Header from "./components/Header";



export const metadata = {
  title:{
    template:'%s|نکست شاپ ',
    default:'نکست شاپ'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body
      >
        <div className="font-display">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
